services:
  family-finance:
    container_name: family_finance_planner
    image: spjts/family-finance:latest
    restart: unless-stopped
    ports:
      - "3999:3000"
    volumes:
      - /mnt/pool1/dockge/configs/family-finance/db:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DATABASE_URL=file:/data/dev.db
      - NODE_ENV=production
      - JWT_SECRET=change-this-to-a-long-random-string
